export {default as aboutgroup} from "./About-The-Group.png"
export {default as team1} from "./WhatsApp Image 2024-11-15 at 5.jpeg"
export {default as team2} from "./nilachal.jpg"
export {default as team3} from "./himanshu.jpg"
export {default as team4} from "./malaya.jpg"
export {default as team5} from "./goutam.jpg"
export {default as team6} from "./Niranjan.jpg"
export {default as team7} from "./Mohapatra.jpg"
export {default as team8} from "./Srikant.jpg"
export {default as team9} from "./Madam.jpg"
export {default as team10} from "./Narayan.jpg"